// Autogenerated code by vite-plugin-svg-sprite-names-typescript
export type IconName = "globe" | "arrow-down" | "sun" | "moon" | "home" | "camera" | "book" | "user" | "folder" | "arrow-right" | "email" | "linkedin" | "github" | "bluesky" | "calendar" | "grid" | "list";
export const IconNameList = ["globe", "arrow-down", "sun", "moon", "home", "camera", "book", "user", "folder", "arrow-right", "email", "linkedin", "github", "bluesky", "calendar", "grid", "list"] as const;
